# Generated by Django 5.1.7 on 2025-04-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_image_postfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostFiles',
            new_name='PostFile',
        ),
    ]
